apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loop-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate-bash
        template: gen-number-list
      - name: generate-python
        template: gen-number-list
      - name: generate-javascript
        template: gen-number-list
    - - name: print-bash
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{steps.generate-bash.outputs.result}}"
      - name: print-python
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{steps.generate-python.outputs.result}}"
      - name: print-javascript
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withParam: "{{steps.generate-javascript.outputs.result}}"

  # Generate a list of numbers in JSON format
  - name: gen-number-list
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import json
        import sys
        json.dump([i for i in range(1, 5)], sys.stdout)

  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo result was: {{inputs.parameters.message}}"]
